TableroMensajes/TableroMensajes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mensajes/',include('mensajes.urls',namespace='mensajes'))
]

TableroMensajes/mensajes/urls.py
from django.urls import path
from .views import ver_mensajes, index

app_name = 'mensajes'

urlpatterns = [
    path('', index,name='index'),
    path('recibidos/', ver_mensajes, name='ver_mensajes'),
]

TableroMensajes/mensajes/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Mensaje(models.Model):
    remitente = models.CharField(max_length=255)
    destinatario = models.CharField(max_length=255)
    texto = models.TextField()
    fecha_hora = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.remitente} a {self.destinatario}: {self.texto}"

    

TableroMensajes/mensajes/views.py
from django.shortcuts import render
from .models import Mensaje

# Create your views here.
def ver_mensajes(request):
    mensajes_recibidos = Mensaje.objects.all().order_by('fecha_hora')

    return render(request, 'mensajes/recibidos.html',{'mensajes' : mensajes_recibidos})

def index(request):
    return render(request,'mensajes/index.html')

TableroMensajes/mensajes/templates/mensajes/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mensajes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container text-center mt-5">
        <h1 class="display-4">Bienvenido a la Aplicación de Mensajes</h1>
        <p class="lead">Haz click en el boton inferior para ver tus mensajes.</p>
        <a href="{% url 'mensajes:ver_mensajes' %}" class="btn btn-primary btn-lg">Ver Mensajes Recibidos</a>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.3/js/bootstrap.min.js"></script>
</body>
</html>

TableroMensajes/mensajes/templates/mensajes/recibidos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mensajes Recibidos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <h1 class="text-center">Mensajes</h1>
        
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Remitente</th>
                    <th>Destinatario</th>
                    <th>Mensaje</th>
                    <th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                {% for mensaje in mensajes %}
                <tr>
                    <td>{{ mensaje.remitente }}</td>
                    <td>{{ mensaje.destinatario}}</td>
                    <td>{{ mensaje.texto }}</td>
                    <td>{{ mensaje.fecha_hora|date:"d/m/Y H:i" }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-center">No hay mensajes disponibles.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.3/js/bootstrap.min.js"></script>
</body>
</html>